---
- include_tasks: setup-RedHat6.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '6'

- include_tasks: setup-RedHat7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- include_tasks: setup-Debian.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'jessie' or ansible_distribution_release == 'stretch'

- include_tasks: setup-Ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial'
      or ansible_distribution_release == 'artful'

- name: Ensure /etc/deceptionlogic/ exists!
  file:
    path: /etc/deceptionlogic/
    state: directory
    mode: 0755

- name: Ensure deception-agent is configured.
  template:
    src: agent.conf.j2
    dest: /etc/deceptionlogic/agent.conf
    mode: 0644

- name: Enable service deception-agent is started and enabled on boot
  service:
    name: deception-agent
    state: started
    enabled: yes