---

- name: Ensure dependencies installed
  yum:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - yum-utils
      - pygpgme

- name: Import gpg key
  rpm_key:
    state: present
    key: "{{ gpg_key_url }}"

- name: get repo file
  get_url:
    url: "{{ rhel7_repo_url }}"
    dest: /tmp/deception-logic-deception-agent.repo

- name: add repo
  command: " yum-config-manager --add-repo /tmp/deception-logic-deception-agent.repo "

- name: Ensure deception-agent installed
  yum:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - deception-agent
